default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: rcore
  password: nein4qua

development:
  <<: *default
  database: rcore

test:
  <<: *default
  database: rcore_test

# production:
#   <<: *default
