default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: rcore
  password: nein4qua

production:
  <<: *default
  database: rcore

development:
  <<: *default
  database: rcore_development

test:
  <<: *default
  database: rcore_test
